query ContestPage($userId: String!) {
  contests(userId: $userId) {
    id
    adminUserId
    name
    date
    memo
  }
}

mutation createContest($input: CreateContestInput!) {
  createContest(input: $input) {
    id
  }
}
